### ISSUE TITLE
💡️[Enhancement]: FileMonitor - Support API Key

### ISSUE THREAD

**Issue by ElCamino-Real** [David-Maisonave/Axter-Stash#1] opened 2024-08-16 21:25 UTC
### If feature request is related to a problem, give a clear and concise description of what is the problem. Ex. I'm always frustrated when [...]

Script fails due to error 401, I presume because I have auth enabled and a API key generated.

### Describe the solution you'd like. A clear and concise description of what you want to happen.

Check for enabled auth and use the API key when querying the GQL endpoint.

**Comment by David-Maisonave** [comment] 2024-08-17 04:33
> Script fails due to error 401, I presume because I have auth enabled and a API key generated.

I'm trying to reproduce this on my end, but after I setup the credentials, Stash started running very slow. I was able to start FileMonitor as a service, and I didn't see any errors.
If I can't reproduce this, I need a lot more details to address it.
1. Exactly when does the failure occur?
2. Can you please provide logging from both FileMonitor (filemonitor.log) and Stash associated with the error?
3. What version of FileMonitor are you running?
4. Are you running it as a service or as a plugin?
5. If you're running it as a service, are you starting it from the command line, or from the UI (Settings->Task->Plugin Tasks->FileMonitor->[Start Library Monitor Service])?

**Comment by David-Maisonave** [comment] 2024-08-17 05:05
This issue needs to be posted as a [plugin bug report](https://github.com/David-Maisonave/Axter-Stash/issues/new?assignees=&labels=Plugin_Bug&projects=&template=bug_report_plugin.yml&title=%F0%9F%AA%B2%5BEnterPluginNameHere%5D+Your_Short_title).

Can you please close this question and open a plugin bug report?
A plugin bug report has additional questions which helps address the issue(s)?
Please also include answers to the question in my previous post.

Thank you.

**Comment by David-Maisonave** [comment] 2024-08-17 07:07
I was able to reproduce this, and created a fix on 0.8.4 version. You can download this version from [Axter-Stash->FileMonitor](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/FileMonitor).

It may be a while before I update the version in the [CommunityScripts->FileMonitor](https://github.com/stashapp/CommunityScripts/tree/main/plugins/FileMonitor).

I don't usually update the CommunityScripts with minor changes, unless it's a serious bug.

With the new 0.8.4 version, open the **filemonitor_config.py**, and look for the apiKey.  Populate that field with your ApiKey, and restart the FileMonitor service.

FYI:
In my setup, FileMonitor worked when started as a plugin without needing the ApiKey. When started as a service is when it failed.

**Closed** 2024-08-17 07:08 UTC

**Comment by David-Maisonave** [comment] 2024-08-17 10:20
I made an additional change which removes the need to populated the API key in the filemonitor_config.py.
The new **0.8.5** version will automatically pass the API Key to the service.

I left the apiKey field in the filemonitor_config.py because it still can be useful if user wants to run the script from the command line.
Otherwise if it's run from the Stash UI as a service, or if it's run as a plugin, the field does not need to be populated.
